// Pull flat object drawings out of an open icon set (downloaded once into vendor/iconify with npm) and recolour them to the
// project's palette, so a reel can use them as props and set dressing without looking pasted in.
//
//   node tools/icons_pull.mjs <reel> <set> name1,name2,…  [--raw]      → videos/<reel>/icons.js   (merged with what is there)
//   node tools/icons_pull.mjs --find <set> <word>                       → names in the set that contain the word
//
// Sets: fluent-emoji-flat (Microsoft Fluent Emoji, MIT — about 3,000 flat-colour objects, no outline, no attribution needed),
//       ph (Phosphor, MIT — line / duotone icons). The licence of a set is read from its own info.json and written into icons.js.
// Recolouring: every fill is moved to the nearest colour of the palette below (CIE Lab distance), so a saturated blue becomes
// our muted blue, a red becomes the brand pink, greys become paper tones. --raw keeps the original colours.
// Brand logos are never pulled: the sets used here have none, and names matching a short block list are refused.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { reelDir } from './paths.mjs';
import { fileURLToPath } from 'node:url';

const LAB = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(LAB, 'vendor', 'iconify', 'package.json'));
const PALETTE = {
  ink: '#111112', night: '#1E2033', body: '#26232B', mute: '#8D8880', line: '#CFC6B8', desk: '#E7E1D8', paper: '#F2EEE8', white: '#FFFFFF',
  pink: '#FF3D72', pinkD: '#D81B5C', pinkL: '#FFD6E2', blue: '#7FA3C9', blueD: '#4F7CAC', blueL: '#DCE8F2', mint: '#9CC5A1', green: '#3FA36B', mintL: '#E1F0E2',
  yellow: '#F2C46D', yellowD: '#D9A441', yellowL: '#FBEFD2', lilac: '#B9A7D9', lilacD: '#8E79B8', lilacL: '#ECE6F6', wood: '#C9A27A', horse: '#B98B5E', horseD: '#8E6440', brownD: '#5E4330',
};
const BLOCK = /logo|brand|flag-|^flag$/;

const hex = (h) => { h = h.replace('#', ''); if (h.length === 3) h = [...h].map((c) => c + c).join(''); return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)); };
const lab = ([r, g, b]) => {
  const f = (v) => { v /= 255; return v > 0.04045 ? ((v + 0.055) / 1.055) ** 2.4 : v / 12.92; };
  const [R, G, B] = [f(r), f(g), f(b)];
  const X = (R * 0.4124 + G * 0.3576 + B * 0.1805) / 0.95047; const Y = R * 0.2126 + G * 0.7152 + B * 0.0722; const Z = (R * 0.0193 + G * 0.1192 + B * 0.9505) / 1.08883;
  const q = (v) => (v > 0.008856 ? Math.cbrt(v) : 7.787 * v + 16 / 116);
  return [116 * q(Y) - 16, 500 * (q(X) - q(Y)), 200 * (q(Y) - q(Z))];
};
const PAL = Object.entries(PALETTE).map(([k, v]) => [k, v, lab(hex(v))]);
const nearest = (c) => { const L = lab(hex(c)); let best = PAL[0]; let bd = 1e9; for (const p of PAL) { const d = (L[0] - p[2][0]) ** 2 + (L[1] - p[2][1]) ** 2 + (L[2] - p[2][2]) ** 2; if (d < bd) { bd = d; best = p; } } return best[1]; };
const recolour = (body) => body.replace(/#[0-9a-fA-F]{3,8}\b/g, (m) => (m.length === 4 || m.length === 7 ? nearest(m) : m));

const args = process.argv.slice(2);
if (args[0] === '--find') {
  const set = require(`@iconify-json/${args[1]}/icons.json`);
  console.log(Object.keys(set.icons).filter((n) => n.includes(args[2]) && !/-(light|dark|medium|medium-light|medium-dark)$/.test(n)).join(' '));
  process.exit(0);
}
const [reel, setName, list] = args; const raw = args.includes('--raw');
if (!reel || !setName || !list) { console.error('usage: node tools/icons_pull.mjs <reel> <set> name1,name2,… [--raw]'); process.exit(1); }
const set = require(`@iconify-json/${setName}/icons.json`); const info = require(`@iconify-json/${setName}/info.json`);
const out = join(reelDir(reel), 'icons.js');
let have = {}; let credits = {};
if (existsSync(out)) { const src = readFileSync(out, 'utf8'); const m = src.match(/export const ICONS = (\{[\s\S]*?\n\});/); const c = src.match(/export const ICON_CREDITS = (\{[\s\S]*?\});/); if (m) have = JSON.parse(m[1]); if (c) credits = JSON.parse(c[1]); }
const missing = [];
for (const name of list.split(',').map((x) => x.trim()).filter(Boolean)) {
  if (BLOCK.test(name)) { console.error(`refused (looks like a logo or flag): ${name}`); continue; }
  const ic = set.icons[name] || (set.aliases && set.aliases[name] && set.icons[set.aliases[name].parent]);
  if (!ic) { missing.push(name); continue; }
  const w = ic.width || set.width || 32; const h = ic.height || set.height || 32;
  have[`${setName === 'fluent-emoji-flat' ? '' : `${setName}:`}${name}`] = { w, h, body: raw ? ic.body : recolour(ic.body) };
}
credits[setName] = `${info.name} — ${info.author.name}, ${info.license.title} (${info.license.url})`;
const js = `// Generated by tools/icons_pull.mjs — object drawings from open icon sets, recoloured to the project palette. Do not edit by hand.
// Sources and licences are in ICON_CREDITS (MIT sets: no attribution required; listed here for the record).
export const ICON_CREDITS = ${JSON.stringify(credits, null, 1)};
export const ICONS = ${JSON.stringify(have, null, 0).replace(/^\{/, '{\n').replace(/\}$/, '\n}').replace(/\},"/g, '},\n"')};
`;
writeFileSync(out, js);
console.log(`${out}: ${Object.keys(have).length} drawings${missing.length ? ` · not in ${setName}: ${missing.join(' ')}` : ''}`);
